--SELECT * FROM BRANDINFO WHERE BRAND = 'CHEVROLET'; --ok!

--SELECT * FROM BRANDINFO WHERE BRAND = 'HYUNDAI'; --ok!

--SELECT * FROM BRANDINFO WHERE BRAND = 'KG_MOBILITY'; --ok!

--SELECT * FROM CARINFO WHERE BRAND = 'HYUNDAI'; --ok!

CREATE TABLE BINFO(
BRAND VARCHAR,
LOC VARCHAR); -- ok!
